"""add manager_phone column to users

Revision ID: a4a6a27e9213
Revises: c8c776365a84
Create Date: 2025-10-07 19:29:39.519577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4a6a27e9213'
down_revision: Union[str, Sequence[str], None] = 'c8c776365a84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('manager_phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'manager_phone')
    # ### end Alembic commands ###
